### ISSUE TITLE
Can you create a new tag 1.0.8 and publish it on NPM?

### ISSUE THREAD

**Issue by labajo** [OpenNebula/addon-nodejs#4]
Hi @apocas 
We are using your library and we need the feature vm.updateConf. Can you publish a new release in the npm repository?

Thank you very much. Your library works pretty well.

**Comment by apocas** [comment]
Hi,

Let me just push a few more things and I will publish a new version later
today :)

Will ping when published.

Pedro Dias

On Apr 10, 2017 14:20, "Juan Antonio Hernando Labajo" <
notifications@github.com> wrote:

Hi @apocas <https://github.com/apocas>
We are using your library and we need the feature vm.updateConf. Can you
publish a new release in the npm repository?

Thank you very much. Your library works pretty well.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/OpenNebula/addon-nodejs/issues/4>, or mute the thread

**Comment by labajo** [comment]
Thank you very much. 😃

**Comment by apocas** [comment]
v1.0.8 published :)
